# Generated by Django 2.2.2 on 2019-06-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Five',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('upper_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasav4.One')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
                ('amount', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField()),
                ('transaction_method', models.CharField(choices=[('cash', 'Nakit'), ('bank', 'Banka'), ('check', 'Çek'), ('credit_card', 'Kredi Kartı')], max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasav4.Five')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kasav4.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('upper_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasav4.Two')),
            ],
        ),
        migrations.CreateModel(
            name='Four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('upper_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasav4.Three')),
            ],
        ),
        migrations.AddField(
            model_name='five',
            name='upper_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasav4.Four'),
        ),
    ]
