# Generated by Django 2.2.2 on 2019-06-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasav4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='five',
        ),
        migrations.AddField(
            model_name='transaction',
            name='four',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasav4.Four'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasav4.One'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasav4.Three'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasav4.Two'),
        ),
    ]
