# Generated by Django 2.2.2 on 2019-06-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasav4', '0002_auto_20190611_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='five',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='giris', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Five',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasav4.Bank'),
        ),
    ]
