# Generated by Django 2.2.2 on 2019-06-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasav4', '0003_auto_20190612_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='one',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kasav4.TransactionType'),
            preserve_default=False,
        ),
    ]
