# Generated by Django 2.2.2 on 2019-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasav4', '0004_auto_20190613_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='isBank',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
