# Generated by Django 2.2.2 on 2019-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasav4', '0005_auto_20190613_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank',
            field=models.ManyToManyField(related_name='receiver_banks', to='kasav4.Bank'),
        ),
    ]
