# Generated by Django 2.2.2 on 2019-06-15 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasav4', '0008_auto_20190615_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_from', to='kasav4.Bank'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_to', to='kasav4.Bank'),
        ),
    ]
